doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                dbname: '%env(APP_DATABASE_NAME)%'
                host: '%env(APP_DATABASE_HOST)%'
                port: '%env(APP_DATABASE_PORT)%'
                user: '%env(APP_DATABASE_USER)%'
                password: '%env(APP_DATABASE_PASSWORD)%'
                charset: utf8mb4
                default_table_options:
                        charset: utf8mb4
                        collate: utf8mb4_unicode_ci
                        row_format: DYNAMIC
                server_version: '8.0'
                mapping_types:
                    json: string

