services:
    akeneo_measure.proxy.structure.is_there_at_least_one_attribute_configured_with_measurement_family:
        class: AkeneoMeasureBundle\Infrastructure\Structure\IsThereAtLeastOneAttributeConfiguredWithMeasurementFamilyProxy
        arguments:
            - '@akeneo.pim.structure.query.is_there_at_least_one_attribute_configured_with_measurement_family'

    akeneo_measure.proxy.security.security_facade:
        class: AkeneoMeasureBundle\Infrastructure\Security\SecurityFacadeProxy
        arguments:
            - '@oro_security.security_facade'
