services:
    akeneo_measurement.public_api.get_unit_translations:
        class: 'AkeneoMeasureBundle\PublicApi\SqlGetUnitTranslations'
        arguments:
            - '@database_connection'
            -
    akeneo_measurement.public_api.onboarder.find_all_measurement_families:
        class: 'AkeneoMeasureBundle\PublicApi\Onboarder\FindAllMeasurementFamilies'
        arguments:
            - '@akeneo_measure.persistence.measurement_family_repository'
