services:
  Akeneo\Connectivity\OctoCouplingDefenseSystem\UserManagement\Implementation\QueryHandler\GetUserById\GetUserByIdHandler:
    arguments:
      - '@pim_user.repository.user'
    tags:
      - { name: messenger.message_handler, bus: query.bus }
