services:
    akeneo_connectivity.connection.persistence.query.select_connections:
        class: 'Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\DbalSelectConnectionsQuery'
        arguments:
            - '@database_connection'

    akeneo_connectivity.connection.persistence.query.select_connection_with_credentials_by_code:
        class: 'Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\DbalSelectConnectionWithCredentialsByCodeQuery'
        arguments:
            - '@database_connection'

    akeneo_connectivity_connection.persistence.query.select_last_connection_business_errors:
        class: Akeneo\Connectivity\Connection\Infrastructure\Persistence\Elasticsearch\Query\ElasticsearchSelectLastConnectionBusinessErrorsQuery
        arguments:
            - '@akeneo_connectivity.client.connection_error'

    akeneo_connectivity_connection.persistence.query.select_all_auditable_connection_code:
        class: Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\SelectAllAuditableConnectionCodeQuery
        arguments:
            - '@database_connection'

    akeneo_connectivity_connection.persistence.query.purge_connection_errors:
        class: Akeneo\Connectivity\Connection\Infrastructure\Persistence\Elasticsearch\Query\PurgeConnectionErrorsQuery
        arguments:
            - '@akeneo_connectivity.client.connection_error'

    Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\IsConnectionsNumberLimitReachedQuery:
        arguments:
            - '@database_connection'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Connections\GetConnectionsNumberLimit'
