version: 2.1
workflows:
    version: 2

    octopus_workflow:
        when:
            not:
                equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        jobs:
            - build_dev_optimized:
                  filters:
                      branches:
                          only:
                              - /CXP-.*/
            - test_front_connectivity:
                  requires:
                      - build_dev_optimized
            - test_back_connectivity:
                  requires:
                      - build_dev_optimized
            - test_marketplace_activate_e2e:
                  requires:
                      - build_dev_optimized
            - test_back_data_migrations:
                  requires:
                      - build_dev_optimized
            - pull_request_success:
                  requires:
                      - test_front_connectivity
                      - test_back_connectivity
                      - test_back_data_migrations

    weekly_octopus_code_quality:
        when:
            and:
                - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
                - equal: [ "weekly_octopus_code_quality", << pipeline.schedule.name >> ]
        jobs:
            - checkout_ce
            - build_dev:
                  is_ee_built: false
                  requires:
                      - checkout_ce
            - test_octopus_code_quality:
                  requires:
                      - build_dev
